### PR TITLE
1 0 active shipping upgrade

### PR DESCRIPTION
**Pull request by jspizziri**
Upgrade active_shipping overrides to be compatible with active_shipping >= 1.0.0.pre1

### CODE REVIEW

**Comment by jspizziri** [comment]
Alright, so this PR will at the very least fix the bug where active_shipping crashes on checkout. I think I maintained all the logic that was in the prior version; however its hard to say because so much dev has been going on with active_shipping.

I'm guessing there are going to be more issues with this until they release a stable version that can be locked in.

**Comment by jspizziri** [comment]
Hold off on this, I need to fix something else real quick.

**Comment by jspizziri** [comment]
There we go, that should do the trick.

**Comment by jspizziri** [comment]
@JDutil I know you're a busy guy, but master 3-0-stable are completely toast until this gets merged in.

**Comment by JDutil** [comment]
Thanks.  I don't use this extension at all so unless I'm mentioned on it I won't receive notifications.  As you're well aware this extension needs additional maintainers since you're the only one stepping up to the plate here I could provide commit access if you want.

**Comment by jspizziri** [comment]
No problem. 

Sure, I'll take on some of the maintenance responsibilities. This is a super important extension for a continued broad acceptance of spree IMO, so I'd hate to see it degrade.

**Comment by JDutil** [comment]
@jspizziri I've sent an invite.  I agree it's an important extension, but surprisingly relatively few people actually use it. More important surprisingly few people actually care about maintaining it.  For continued broad acceptance of Spree we need a thriving community of contributors maintaining the projects they find important.

**Comment by jspizziri** [comment]
:+1: I agree I've recently been on a rampage to get several projects upgraded to 3.0.

**Pull request closed without merging**
